name: 'ducks-tinder-client'
services:
  nginx:
    container_name: nginx
    image: nginx:1.27.2-alpine
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf.template
      - ./cert:/etc/nginx/cert
    env_file:
    - .env.dev
    ports:
      - '${PROXY_PORT}:${PROXY_PORT}'
    command: >
      /bin/sh -c "envsubst '
      \$\{PROXY_PORT\}
      \$\{CLIENT_URL\}
      \$\{PROXY_USER_SERVICE\}
      \$\{PROXY_CHAT_SERVICE\}
      \$\{PROXY_AUTH_SERVICE\}
      \$\{AUTH_SERVICE_URL\}
      \$\{USER_SERVICE_URL\}
      \$\{CHAT_SERVICE_URL\}
      ' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
